name: kontinum_frontend_build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:

jobs:
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn install

      - name: build the project using Yarn
        working-directory: ./frontend
        run: yarn build
